Bump up rapidjson version to latest in CCI
RapidJson 1.1.0 has a bug in `document.h` which is currently an issue on a fresh install. Probably due to changing of the order of includes in CuraEngine.

```
error: assignment of read-only member ‘rapidjson::GenericStringRef<CharType>::length’
```