Use full specified type
Although the old code compiles on more modern OSes and compilers it fails,
on one our runners with Macos 10.15 with:

```
/Users/runner/.conan/data/curaengine/5.1.0-alpha+330/ultimaker/cura_9365/build/f93f32bc25d44780c2d256b52bbd6be4fd146bc2/src/utils/ThreadPool.h:233:117: error: member reference base type 'MultipleProducersOrderedConsumer' is not a structure or union
    MultipleProducersOrderedConsumer(first, last, std::forward<P>(producer), std::forward<C>(consumer), max_pending).run(*thread_pool);
```

Probably because the template arguments weren't provided. Since I'm currently
working on a system where it does compile, this fix is a stab in the dark.
And we will find out after a push.

Contributes to CURA-9365